name: Sync to Tsinghua Git
on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Remove Workflows
        run: |
          rm -rf .github/workflows

      - name: Push to Tsinghua Git
        env:
          TSINGHUA_TOKEN: ${{ secrets.TSINGHUA_GIT_TOKEN }}
        run: |
          git remote add tsinghua "https://oauth2:${TSINGHUA_TOKEN}@git.tsinghua.edu.cn/yunyang-21/DormScoreRegister.git"
          git push tsinghua HEAD:main --tags --force

  sync_release:
    runs-on: ubuntu-latest
    needs: sync_code
    if: github.event_name == 'release'
    steps:
      - name: Download Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --clobber

      - name: Get Release Info
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -sH "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }})
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$(echo "$RESPONSE" | jq -r '.body')" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitLab Release
        env:
          GITLAB_TOKEN: ${{ secrets.TSINGHUA_GIT_TOKEN }}
        run: |
          curl --request POST \
            --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            --data "name=${{ github.ref_name }}" \
            --data "tag_name=${{ github.ref_name }}" \
            --data "description=${{ steps.release.outputs.description }}" \
            "https://git.tsinghua.edu.cn/api/v4/projects/27745/releases"

      - name: Upload Assets to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.TSINGHUA_GIT_TOKEN }}
        run: |
          for asset in $(ls); do
            if [ "$asset" != ".github" ]; then
              curl --request POST \
                --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
                --form "file=@$asset" \
                "https://git.tsinghua.edu.cn/api/v4/projects/27745/releases/${{ github.ref_name }}/assets/links"
            fi
          done
